version: '3.8'

services:
  fastapi-book-project:   
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network  

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fastapi-book-project  
    networks:
      - app_network 


networks:
  app_network:
    driver: bridge
