name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Railway Deployment
        run: |
          curl -X POST "https://api.railway.app/v1/projects/${{ secrets.RAILWAY_PROJECT_ID }}/deployments" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
          --data '{"branch": "main"}'
