name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Setup virtual environment
      - name: Setup Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      # Upgrade pip and install dependencies
      - name: Install Dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install fastapi
          pip install -r requirements.txt

      # Start FastAPI application
      - name: Start FastAPI Application
        run: |
          source venv/bin/activate
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &

      # Install and Start ngrok
      - name: Start ngrok Tunnel
        run: |
          sudo apt update
          sudo apt install -y jq
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 8000 > ngrok.log 2>&1 &

      # Fetch ngrok URL and display it
      - name: Fetch ngrok URL
        run: |
          sleep 5
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok tunnel running at: $NGROK_URL"
